### ISSUE TITLE
OPTIONAL parameter LambdaZipsBucketName used unconditionally throughout cloudbees-core-existing-cluster.template.yaml

### ISSUE THREAD

**Issue by fernandoespinosa** [aws-quickstart/quickstart-cloudbees-core#10]
# Issue

When tying to deploy to an existing EKS cluster using template _cloudbees-core-existing-cluster.template.yaml_ the OPTIONAL parameter `LambdaZipsBucketName` is used unconditionally in `Custom::CopyZips` and all `AWS::Lambda::Function` resources.

While condition `CreateLambdaZipsBucket` based on presence of `LambdaZipsBucketName` is effectively used to create an S3 bucket, this bucket is never actually used.

**Comment by schottsfired** [comment]
Hi @fernandoespinosa, thanks so much for reporting the issue and filling a pull request. I'll take a look.

**Comment by schottsfired** [comment]
Hi @fernandoespinosa, happy to see that this was merged not only into our Quick Start but also will be added to the EKS framework (see PR). Thank you for taking the time to look into this and especially for proposing the solution.

**Comment by schottsfired** [comment]
Hi @jaymccon can we close this issue? The originally reported issue was fixed, and we've since disabled the existing cluster deployment option.
